In [24]:
import numpy as np

rrt_data = np.loadtxt("rrt_data.txt", delimiter=',')
rrt_star_data = np.loadtxt("rrt_star_data.txt", delimiter=',')

rrt_mean = np.zeros(5)
rrt_star_mean = np.zeros(5)

# TIME | UPD_PATH | NODES NUM | DIST | RRT_PROC_TIME

for i in range(5):
    rrt_mean[i] = np.mean(rrt_data[:,i])
    rrt_star_mean[i] = np.mean(rrt_star_data[:,i])

print(rrt_data[0,:])
print(rrt_star_data[0,:])
print(rrt_mean)
print(rrt_star_mean)

[2.1420e+03 4.0000e+00 2.2000e+01 1.1158e+03 2.9000e-01]
[2365.      3.     22.    993.59    2.45]
[1.88177e+03 2.94000e+00 1.90300e+01 9.53555e+02 1.63200e-01]
[1861.57      3.01     19.19    898.5175    2.661 ]
